spring.application.name=tinjaku

spring.datasource.url=jdbc:postgresql://localhost:5432/tinjaku
spring.datasource.username=postgres
spring.datasource.password=025885

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
